- alias: Synchronize IOT devices on HA start-up
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff_S2X_Desktop/POWER"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "home/BedLEDStrip"
        payload: ""
